# Generated by Django 5.1.2 on 2024-11-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("cliente_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("region", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usuario_id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("contacto", models.CharField(max_length=100, unique=True)),
                ("region", models.CharField(default="Desconocida", max_length=50)),
                ("contraseña", models.CharField(max_length=100)),
                ("rol", models.CharField(default="conductor", max_length=50)),
                ("tipo_documento", models.CharField(default="DNI", max_length=50)),
                ("documento", models.CharField(default="00000000", max_length=50)),
                (
                    "fecha_nacimiento",
                    models.DateField(blank=True, default="2000-01-01", null=True),
                ),
                ("telefono", models.CharField(default="0000000000", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("producto_id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=50)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("registro", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                ("ubicacion_id", models.AutoField(primary_key=True, serialize=False)),
                ("referencia", models.CharField(max_length=102)),
                ("latitud", models.DecimalField(decimal_places=18, max_digits=22)),
                ("longitud", models.DecimalField(decimal_places=18, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "placa",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("soat", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                ("registro", models.DateField(auto_now_add=True)),
                ("año_fabricacion", models.IntegerField()),
                (
                    "maximo_recorrido_diario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "maxima_capacidad",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_recorrido",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "capacidad",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("estado", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("pedido_id", models.AutoField(primary_key=True, serialize=False)),
                ("registro", models.DateField(auto_now_add=True)),
                ("peso_total", models.DecimalField(decimal_places=3, max_digits=10)),
                ("estado", models.CharField(max_length=20)),
                (
                    "volumen",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.cliente"
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.ubicacion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recorrido",
            fields=[
                ("recorrido_id", models.AutoField(primary_key=True, serialize=False)),
                ("hora_salida", models.TimeField()),
                ("fecha", models.DateField()),
                ("hora_entrada", models.TimeField()),
                ("estado", models.CharField(max_length=20)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.vehiculo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                ("envio_id", models.AutoField(primary_key=True, serialize=False)),
                ("registro", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=20)),
                ("hora_llegada", models.TimeField()),
                ("anticipado", models.BooleanField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pedido"
                    ),
                ),
                (
                    "recorrido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.recorrido"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.usuario",
                    ),
                ),
                ("breve", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=20)),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.vehiculo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Linea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.IntegerField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pedido"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.producto"
                    ),
                ),
            ],
            options={
                "unique_together": {("pedido", "producto")},
            },
        ),
    ]
