# Generated by Django 5.1.2 on 2024-11-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_apellido', models.CharField(max_length=255)),
                ('cliente_registro', models.DateField(auto_now_add=True)),
                ('cliente_telefono', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('modelo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('rol_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('documento_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('documento_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('ubicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('latitud', models.DecimalField(decimal_places=18, max_digits=22)),
                ('longitud', models.DecimalField(decimal_places=18, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('conductor_id', models.AutoField(primary_key=True, serialize=False)),
                ('conductor_brevete', models.CharField(max_length=9)),
                ('conductor_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_registro', models.DateField(auto_now_add=True)),
                ('pedido_peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido_volumen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido_precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido_fallos', models.IntegerField(default=0)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('pedido_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('ubicacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('recorrido_id', models.AutoField(primary_key=True, serialize=False)),
                ('recorrido_carga', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorrido_distancia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorrido_fecha_salida', models.DateField(blank=True, null=True)),
                ('recorrido_hra_salida', models.TimeField(blank=True, null=True)),
                ('recorrido_registro', models.DateField(auto_now_add=True)),
                ('conductor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conductor')),
                ('recorrido_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('envio_id', models.AutoField(primary_key=True, serialize=False)),
                ('envio_anterior', models.IntegerField(blank=True, null=True)),
                ('envio_hra_entrega', models.DateTimeField(blank=True, null=True)),
                ('envio_registro', models.DateField(auto_now_add=True)),
                ('envio_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('recorrido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('docusuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('docusuario_valor', models.IntegerField()),
                ('docusuario_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('producto_registro', models.DateField(auto_now_add=True)),
                ('producto_volumen', models.DecimalField(decimal_places=2, max_digits=6)),
                ('producto_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('producto_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nombre', models.CharField(max_length=255)),
                ('usuario_apellido', models.CharField(max_length=255)),
                ('usuario_contraseña', models.CharField(max_length=200)),
                ('usuario_email', models.CharField(max_length=100)),
                ('usuario_fecha_nac', models.DateField(blank=True, null=True)),
                ('usuario_telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('usuario_registro', models.DateField(auto_now_add=True)),
                ('usuario_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.documentousuario')),
                ('usuario_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('usuario_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rolusuario')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehiculo_placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('vehiculo_soat', models.IntegerField()),
                ('vehiculo_año_fabri', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehiculo_max_dist_dia', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehiculo_capacidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vehiculo_reg', models.DateField(auto_now_add=True)),
                ('vehiculo_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.color')),
                ('vehiculo_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('vehiculo_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.marca')),
                ('vehiculo_modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modelo')),
            ],
        ),
        migrations.AddField(
            model_name='recorrido',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculo_placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculo'),
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.IntegerField()),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('pedido_id', 'producto_id')},
            },
        ),
    ]
