# Generated by Django 5.1.2 on 2024-11-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_vehiculo_vehiculo_estado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrovehiculo",
            old_name="vehiculo_id",
            new_name="vehiculo_placa",
        ),
        migrations.AlterUniqueTogether(
            name="registrovehiculo",
            unique_together={("vehiculo_placa", "estado_id")},
        ),
    ]
