# Generated by Django 5.1.2 on 2024-12-01 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_vehiculo_id_registrovehiculo_vehiculo_placa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroConductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registro", models.DateField(auto_now_add=True)),
                (
                    "conductor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.conductor"
                    ),
                ),
                (
                    "estado_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.estado",
                    ),
                ),
            ],
            options={
                "unique_together": {("conductor_id", "estado_id")},
            },
        ),
    ]
