# Generated by Django 5.1.2 on 2024-12-02 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_registroconductor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="usuario_estado",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.estado",
            ),
        ),
    ]
